name: Deploy Nuxt Build to Hosting

on:
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0

    - name: Install Dependencies
      run: npm install

    - name: Create .env.production
      run: |
        echo "API_URL=${{ secrets.NUXT_API_URL }}" > .env.production

    - name: Generate Nuxt App
      run: npm run build:prod

   # 🔥 upload langsung build.zip (tanpa zip ulang)
    - name: Upload build.zip via FTP (FAST)
      run: |
          curl -T .output/build.zip ftp://${{ secrets.FTP_SERVER }}/public_html/ \
          --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}

    # 🚀 trigger extract otomatis
    - name: Extract on Server
      run: curl https://${{ secrets.DOMAIN }}/extract.php
